/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.graphic;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author User
 */
public class GraphicDoraemon extends javax.swing.JFrame {

    /**
     * Creates new form GraphicDoraemon
     */
    public GraphicDoraemon() {
        initComponents();
        setSize(600,1000);
    }
  public void paint(Graphics g){
      g.setColor(Color.lightGray);
      g.fillRect(0,0,getWidth(), getHeight());     
        // Arms
        g.setColor(Color.blue);
        g.fillOval(50, 380, 450, 80);  
        
        // Hands
        g.setColor(Color.white);
        g.fillOval(30, 395, 50, 50); // Left hand
        g.fillOval(470, 395, 50, 50); // Right hand
         // Legs
        g.setColor(Color.blue);
        g.fillOval(160, 520, 120, 160); // Left leg
        g.fillOval(280, 520, 120, 150); // Right leg

        // Body
        g.setColor(Color.blue);
        g.fillOval(150, 370, 250, 250);
        g.setColor(Color.white);
        g.fillOval(175, 370, 200, 200);

       // Head
        g.setColor(Color.blue);
        g.fillOval(180, 180, 200, 200);
        g.setColor(Color.white);
        g.fillOval(205, 230, 150, 150);
        // Eyes
        g.setColor(Color.white);
        g.fillOval(230, 210, 50, 60);
        g.fillOval(280, 210, 50, 60);
        g.setColor(Color.BLACK);
        g.drawOval(230, 210, 50, 60);
        g.drawOval(280, 210, 50, 60);
        g.setColor(Color.black);
        g.fillOval(250, 220, 20, 30);
        g.fillOval(290, 220, 20, 30);

        // Nose
        g.setColor(Color.red);
        g.fillOval(265, 250, 30, 30);
        // Mouth
        g.setColor(Color.black);
        g.drawArc(240, 300, 80, 40, 0, -180);
        g.drawLine(280, 280, 280, 340);
        // Whiskers
        g.drawLine(220, 275, 270, 285);
        g.drawLine(220, 300, 270, 300);
        g.drawLine(220, 325, 270, 315);
        g.drawLine(290, 315, 340, 325);
        g.drawLine(290, 300, 340, 300);
        g.drawLine(290, 285, 340, 275);
       
        // Feet
        g.setColor(Color.white);
        g.fillOval(165, 630, 100, 50); // Left foot
        g.fillOval(290, 630, 100, 50); // Right foot
        
        // Bell
        g.setColor(Color.RED);
        g.fillOval(225, 370, 110, 10);
        g.setColor(Color.yellow);
        g.fillOval(265, 365, 30, 30);
        g.setColor(Color.black);
        g.drawLine(285, 380, 295, 380);
        g.drawOval(275, 375, 10, 10);
        g.drawLine(275, 380, 265, 380);
// Pocket
        g.setColor(Color.BLACK);
        g.drawArc(230, 440, 100, 80, 0, -180);
        g.drawLine(230, 480, 330, 480);
        
    
        
  }
 

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GraphicTest in java");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicDoraemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicDoraemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicDoraemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicDoraemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicDoraemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
